#
 version 7.1.070, Release 1124
#
 sysname SW-ARTHUR
#
#
 scheduler logfile size 16
#
line class aux
 user-role network-admin
#
line class vty
 user-role network-operator
#
line aux 0
 user-role network-admin
#
line vty 0 63
 authentication-mode scheme
 user-role network-operator
 command authorization
 command accounting
#
 ip route-static 0.0.0.0 0 10.100.65.1
#
 info-center loghost 10.100.65.119
#
 ntp-service enable
 ntp-service unicast-server 200.160.7.186
#
 ip http enable
#
return
