services:
  syslogserver:
    container_name: syslogserver
    image: arthurcadore/my-syslogserver:1.0.0
    restart: unless-stopped
    ports:
      - "514:514/udp"
    env_file:
      - ./env/.syslog.env
    healthcheck:
      test: ["CMD", "bash", "-c", "netstat -uln | grep -q ':514 '"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    privileged: true
    networks:
      infra_backend:
        aliases:
          - syslogserver
      infra_frontend:
        aliases:
          - syslogserver

networks:
  infra_frontend:
    external: true
  infra_backend:
    external: true