{
 "title": "Syslog Server Dashboard V2",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "History Logs Register",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(\r\n    CONCAT(YEAR(CURDATE()), '-', \r\n           CASE\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'Jan' THEN '01'\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'Feb' THEN '02'\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'Mar' THEN '03'\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'Apr' THEN '04'\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'May' THEN '05'\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'Jun' THEN '06'\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'Jul' THEN '07'\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'Aug' THEN '08'\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'Sep' THEN '09'\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'Oct' THEN '10'\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'Nov' THEN '11'\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'Dec' THEN '12'\r\n           END, \r\n           '-', \r\n           LPAD(TRIM(SUBSTRING(datetime, 5, 2)), 2, '0'), ' ',\r\n           SUBSTRING(datetime, 8, 2), ':', SUBSTRING(datetime, 11, 2), ':00'\r\n    ),\r\n    '%Y-%m-%d %H:%i:%s'\r\n  ) AS minute_interval,\r\n  COUNT(host) AS host_count\r\nFROM\r\n  logs\r\nGROUP BY\r\n  minute_interval\r\nORDER BY\r\n  minute_interval;"
    }
   ]
  },
  {
   "title": "Top 10 - Log Programs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    SUBSTRING(program, 5) AS program_trimmed,\r\n    COUNT(*) AS log_count\r\nFROM \r\n    logs\r\nWHERE \r\n    program LIKE '%%10%' \r\nGROUP BY \r\n    program_trimmed\r\nORDER BY \r\n    log_count DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT id AS total_logs FROM logs\r\nORDER BY id DESC\r\nlimit 1;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 17, "w": 17, "x": 7, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT id, source_ip, host, message\r\nFROM logs\r\nWHERE program != ''\r\nORDER BY id DESC\r\nlimit 100;\r\n\r\n"
    }
   ]
  },
  {
   "title": "Top 10 - Hosts",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT source_ip, host, COUNT(*) AS log_count\r\nFROM logs\r\nWHERE source_ip != ''\r\nGROUP BY source_ip, host\r\nORDER BY log_count DESC\r\nLIMIT 10;\r\n"
    }
   ]
  }
 ]
}