#############################################################################
# Default syslog-ng.conf file which collects all local logs into a
# single file called /var/log/messages tailored to container usage.
#
# The changes from the stock, default syslog-ng.conf file is that we've
# dropped the system() source that is not needed and that we enabled network
# connections using default-network-drivers(). Customize as needed and
# override using the -v option to docker, such as:
#
#  docker run ...  -v "$PWD/syslog-ng.conf":/etc/syslog-ng/syslog-ng.conf
#

@version: 4.4
@include "scl.conf"

source s_local {
        internal();
};

source s_network {
        default-network-drivers();
};

destination d_mysql {
    sql(type(mysql)
    host("syslogdb") username("syslogserver") password("Syslog#123db")
    database("syslogdb")
    table("logs")
    columns("datetime varchar(16)", "host varchar(32)", "program  varchar(20)", "pid varchar(8)", "message  varchar(200)")
    values("${R_DATE}", "${HOST}", "${PROGRAM}", "${PID}", "${MSGONLY}")
    indexes("datetime", "host", "program", "pid", "message"));
};

log {
        source(s_local);
        source(s_network);
        destination(d_mysql);
};
