{
 "title": "Syslog Server Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT id AS total_logs FROM logs\r\nORDER BY id DESC\r\nlimit 1;"
    }
   ]
  },
  {
   "title": "History Logs Register",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(\r\n    CONCAT(YEAR(CURDATE()), '-', \r\n           CASE\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'Jan' THEN '01'\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'Feb' THEN '02'\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'Mar' THEN '03'\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'Apr' THEN '04'\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'May' THEN '05'\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'Jun' THEN '06'\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'Jul' THEN '07'\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'Aug' THEN '08'\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'Sep' THEN '09'\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'Oct' THEN '10'\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'Nov' THEN '11'\r\n             WHEN SUBSTRING(datetime, 1, 3) = 'Dec' THEN '12'\r\n           END, \r\n           '-', \r\n           LPAD(TRIM(SUBSTRING(datetime, 5, 2)), 2, '0'), ' ',\r\n           SUBSTRING(datetime, 8, 2), ':', SUBSTRING(datetime, 11, 2), ':00'\r\n    ),\r\n    '%Y-%m-%d %H:%i:%s'\r\n  ) AS minute_interval,\r\n  COUNT(host) AS host_count\r\nFROM\r\n  logs\r\nGROUP BY\r\n  minute_interval\r\nORDER BY\r\n  minute_interval;"
    }
   ]
  },
  {
   "title": "Top 10 - Hosts",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT host, COUNT(*) AS log_count\r\nFROM logs\r\nWHERE host != ''\r\nGROUP BY host\r\nORDER BY log_count DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Last 100 Log Lines",
   "type": "table",
   "gridPos": { "h": 16, "w": 14, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT id, host, message\r\nFROM logs\r\nWHERE program != ''\r\nORDER BY id DESC\r\nlimit 100;\r\n\r\n"
    }
   ]
  },
  {
   "title": "Top 10 - Log Types",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT program, COUNT(*) AS log_count\r\nFROM logs\r\nWHERE program != ''\r\nGROUP BY program\r\nORDER BY log_count DESC\r\nLIMIT 10;\r\n"
    }
   ]
  }
 ]
}